add error to test email quickly

diff --git a/.github/workflows/nightly-backward-compatibility.yml b/.github/workflows/nightly-backward-compatibility.yml
--- a/.github/workflows/nightly-backward-compatibility.yml
+++ b/.github/workflows/nightly-backward-compatibility.yml
@@ -28,6 +28,12 @@ jobs:
       cardano_node_version: ${{ steps.set-env.outputs.cardano_node_version }}
       signed-entity-types: ${{ steps.set-env.outputs.signed-entity-types }}
     steps:
+      - name: Simulating error
+        shell: bash
+        run: |
+          echo "Simulating failure..."
+          exit 1
+
       - name: Prepare env variables
         id: set-env
         shell: bash
diff --git a/.github/workflows/nightly-docker-builds.yml b/.github/workflows/nightly-docker-builds.yml
--- a/.github/workflows/nightly-docker-builds.yml
+++ b/.github/workflows/nightly-docker-builds.yml
@@ -23,6 +23,12 @@ jobs:
       CONTEXT: .
 
     steps:
+      - name: Simulating error
+        shell: bash
+        run: |
+          echo "Simulating failure..."
+          exit 1
+
       - name: Checkout
         uses: actions/checkout@v4
 
